title: Meta
type: object
additionalProperties: false
properties:
  entity:
    description: The URI of the entity that the meta post describes.
    type: string
    format: uri
    required: true
  servers:
    description: The servers that represent the entity.
    type: array
    required: true
    items:
      type: object
      additionalProperties: false
      properties:
        version:
          description: The Tent version that the server supports.
          type: string
          required: true
        preference:
          description: Indicates the preference to be used when choosing a server to contact. `0` is the most preferred.
          type: integer
          required: true
        urls:
          description: The URLs for this server's Tent API endpoints.
          type: object
          additionalProperties: false
          properties:
            oauth_auth:
              description: The endpoint for the OAuth 2.0 Authorization Request.
              type: string
              format: uri
              required: true
            oauth_token:
              description: The endpoint for the OAuth 2.0 Token Request.
              type: string
              format: uri
              required: true
            posts_feed:
              description: The endpoint that serves lists of posts.
              type: string
              format: uri
              required: true
            new_post:
              description: The endpoint used to create new posts that don't have an identifier assigned.
              type: string
              format: uri
              required: true
            post:
              description:
                The endpoint used to retrieve and update a single post. The `{entity}` and `{post}` variables must be
                replaced with the URL parameter encoded entity URL and post identifier respectively.
              type: string
              format: uri
              required: true
            post_attachment:
              description:
                The endpoint that redirects to an `attachment` URL, used to download an attachment when the digest
                is unspecified.  The `{entity}`, `{post}`, `{version}`, and `{name}` variables must be replaced with the
                URL-encoded publishing entity URL, post identifier, post version, and attachment name respectively. The
                `{version}` variable may be set to `latest` instead of specifying a version.
              type: string
              format: uri
              required: true
            attachment:
              description:
                The endpoint used to retrieve an attachment given a hex-encoded digest. The `{entity}` and `{digest}`
                variables must be replaced with the URL-encoded publishing entity URL and attachment digest
                respectively.
              type: string
              format: uri
              required: true
            batch:
              description: The endpoint used to make batch requests to the server.
              type: string
              format: uri
              required: true
            server_info:
              description: The endpoint where metadata specific to the server is available.
              type: string
              format: uri
              required: true
